---
# YAML documents begin with the document separator ---
 
# The minus in YAML this indicates a list item.  The playbook contains a list
# of plays, with each play being a dictionary
-
 
  # Target: where our play will run and options it will run with
  hosts: all

  # Task: the list of tasks that will be executed within the play, this section
  # can also be used for pre and post tasks
  tasks:
    - name: Creating a directory
      file:
        path: /etc/ansible/facts.d
        recurse: yes
        state: directory

    - name: Copying getdate1 to facts.d directory
      copy:
        src: /etc/ansible/facts.d/getdate1.fact
        dest: /etc/ansible/facts.d/
        mode: 0755

    - name: Copying getdate2 to facts.d directory
      copy:
        src: /etc/ansible/facts.d/getdate2.fact
        dest: /etc/ansible/facts.d/
        mode: 0755

    - name: Refresh Facts
      setup:
    
    - name: Show IP Address
      debug:
        msg: "{{ ansible_default_ipv4.address }}"

    - name: Show custom Fact 1
      debug:
        msg: "{{ ansible_local.getdate1.date }}"

    - name: Show custom Fact 2
      debug:
        msg: "{{ ansible_local.getdate2.date }}"

    - name: Show Custom Fact 1 in hostvars 
      debug:
        msg: "{{ hostvars[ansible_hostname].ansible_local.getdate1.date }}"

    - name: Show Custom Fact 2 in hostvars
      debug:
        msg: "{{hostvars[ansible_hostname].ansible_local.getdate2.date.date }}"



# Three dots indicate the end of a YAML document
...
